In [1]:
import numpy as np
import pandas as pd

In [4]:
data=pd.read_csv("C:/Users/Lenovo/Downloads/data1.csv")
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  74000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
data.shape

(10, 4)

In [11]:
#independent
x = data[['Country','Age','Salary']].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 74000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
#dependent
y=data[['Purchased']].values
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [12]:
#finding missing values
print(data.isnull().sum())

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64


In [13]:
print(data.describe())

             Age        Salary
count   9.000000      9.000000
mean   38.777778  63222.222222
std     7.693793  11584.232579
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000


In [17]:
#drop missing value
data.dropna(inplace=True)
data

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
5   France  35.0  58000.0       Yes
7   France  48.0  74000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [21]:
from sklearn.impute import SimpleImputer


In [22]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [23]:
imputer=imputer.fit(x[:,1:3])

In [25]:
#transform mean
x[:,1:3]=imputer.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63222.22222222222],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 74000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [38]:
from sklearn.preprocessing import LabelEncoder

In [41]:
label_encode_x=LabelEncoder()
label_encode_y=LabelEncoder()

In [42]:
x[:,0]=label_encode_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63222.22222222222],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 74000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [44]:
label_encode_x.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [45]:
y=label_encode_y.fit_transform(y)
y

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=1)

In [48]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[1 40.0 63222.22222222222]
 [0 44.0 72000.0]
 [2 38.0 61000.0]
 [2 27.0 48000.0]
 [0 48.0 74000.0]
 [1 50.0 83000.0]
 [0 35.0 58000.0]]
[[1 30.0 54000.0]
 [0 37.0 67000.0]
 [2 38.77777777777778 52000.0]]
[1 0 0 1 1 0 1]
[0 1 0]


In [49]:
from sklearn.preprocessing import StandardScaler

In [50]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.fit_transform(x_test)
print(x_train)
print(x_test)

[[ 0.17149859 -0.03891021 -0.22152828]
 [-1.02899151  0.50583275  0.59517263]
 [ 1.37198868 -0.31128169 -0.428288  ]
 [ 1.37198868 -1.80932482 -1.63783238]
 [-1.02899151  1.0505757   0.78125639]
 [ 0.17149859  1.32294718  1.61863327]
 [-1.02899151 -0.71983891 -0.70741363]]
[[ 0.         -1.38802721 -0.55138018]
 [-1.22474487  0.45941746  1.40351318]
 [ 1.22474487  0.92860975 -0.852133  ]]
